### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by breadadams**

### CODE REVIEW

**Comment by breadadams** [comment]
I just noticed, on Medium they blur the focus on click, maybe `:focus` styles should be controlled via an `allowFocus` prop 🤔

**Comment by Kikobeats** [comment]
@breadadams not sure if I understand your comment, can you attach a gif demo?

**Comment by breadadams** [comment]
Tricky to display with a gif. What I'm saying is that on _Medium_'s clap button, they don't allow for `:focus` of the element; ie. you cannot click it once or tab to it and then "clap" via the space-bar/return key (as you can with react-clap-button).

I don't think this is a bad thing, but a prop to **disable** allowing focus on the clap button could be a nice feature.

**Comment by Kikobeats** [comment]
oh, I understand, probably to avoid people spam claps, right?

We can do the same!

**Pull request merged**
